[package]
name = "mini-dbg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.24.1"
gimli = "0.26.2"
object = "0.29.0"
addr2line = "0.18.0"
memmap2 = "0.5.5"